FROM gettyimages/spark
ENV http_proxy=http://hzha:Th0ughtW0rkerk@caa-proxybr.co.i.caa.ca:8080
ENV https_proxy=https://hzha:Th0ughtW0rkerk@caa-proxybr.co.i.caa.ca:8080
RUN apt-get update && apt-get install -y net-tools && apt-get install -y vim
