version: "3"

services:
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      webnet:
        ipv4_address: 192.168.33.15

networks:
 webnet:
   external:
     name: shared_nw
      